from typing import Protocol

from tmis.cabinet_os.subscriptions.schemas import PlanTier, Subscription, UsageCounters


class SubscriptionStorePort(Protocol):
    def get(self, firm_id: str) -> Subscription | None: ...

    def save(self, subscription: Subscription) -> None: ...


class UsageStorePort(Protocol):
    def get(self, firm_id: str) -> UsageCounters | None: ...

    def save(self, usage: UsageCounters) -> None: ...


class SubscriptionEnginePort(Protocol):
    """Port implemented by every interchangeable subscription engine."""

    def subscribe(self, firm_id: str, plan: PlanTier) -> Subscription: ...

    def change_plan(self, firm_id: str, plan: PlanTier) -> Subscription: ...

    def cancel(self, firm_id: str) -> Subscription: ...

    def get(self, firm_id: str) -> Subscription: ...

    def record_ai_usage(self, firm_id: str, requests: int) -> UsageCounters: ...

    def record_storage_usage(self, firm_id: str, gb: float) -> UsageCounters: ...

    def set_active_users(self, firm_id: str, count: int) -> UsageCounters: ...

    def has_capacity(self, firm_id: str, dimension: str) -> bool: ...

    def usage(self, firm_id: str) -> UsageCounters: ...
