import json

from tmis.platform_sdk.plugin_system.schemas import PluginType

_BASE_CLASS_BY_TYPE: dict[PluginType, tuple[str, str]] = {
    PluginType.AGENT: ("tmis.platform_sdk.agent_sdk.base", "BaseAgentPlugin"),
    PluginType.CONNECTOR: ("tmis.platform_sdk.connector_sdk.base", "BaseConnectorPlugin"),
    PluginType.DOCUMENT_TEMPLATE: (
        "tmis.platform_sdk.document_sdk.base",
        "BaseDocumentTemplatePlugin",
    ),
    PluginType.TOOL: ("tmis.platform_sdk.sdk.ports", "PluginPort"),
}

_PYTHON_STUB = '''"""{plugin_id} — scaffolded by `tmis platform-sdk create-plugin`."""

from typing import Any

from {module} import {base_class}
from tmis.platform_sdk.sdk.schemas import PluginContext


class {class_name}({base_class}):
    def __init__(self) -> None:
        super().__init__(plugin_id="{plugin_id}")

    async def invoke(self, context: PluginContext, payload: dict[str, Any]) -> dict[str, Any]:
        raise NotImplementedError("TODO: implement {plugin_id}")
'''

_WORKFLOW_STUB = {
    "id": "{plugin_id}",
    "name": "{plugin_id}",
    "steps": [{"id": "step-1", "name": "First step", "action": "noop"}],
    "trigger_events": [],
    "validations": [],
}


def _class_name(plugin_id: str) -> str:
    return "".join(part.capitalize() for part in plugin_id.replace("-", "_").split("_")) + "Plugin"


def manifest_scaffold(plugin_id: str, plugin_type: PluginType, author: str) -> dict[str, object]:
    return {
        "id": plugin_id,
        "name": plugin_id.replace("-", " ").title(),
        "version": "0.1.0",
        "plugin_type": plugin_type.value,
        "author": author,
        "description": "TODO: describe this plugin",
        "license": "MIT",
        "permissions": [],
        "dependencies": [],
        "compatibility": "*",
    }


def render_plugin_scaffold(
    plugin_id: str, plugin_type: PluginType, author: str
) -> dict[str, str]:
    """Renders the sprint's plugin scaffold (see the "CLI" spec's
    `create-plugin` command) as a `{filename: content}` mapping —
    string templates only, never generated by executing anything."""
    files = {
        "manifest.json": json.dumps(
            manifest_scaffold(plugin_id, plugin_type, author), indent=2, ensure_ascii=False
        )
    }
    if plugin_type is PluginType.WORKFLOW:
        workflow = dict(_WORKFLOW_STUB)
        workflow["id"] = plugin_id
        workflow["name"] = plugin_id
        files["workflow.json"] = json.dumps(workflow, indent=2, ensure_ascii=False)
    else:
        module, base_class = _BASE_CLASS_BY_TYPE[plugin_type]
        files["plugin.py"] = _PYTHON_STUB.format(
            plugin_id=plugin_id,
            module=module,
            base_class=base_class,
            class_name=_class_name(plugin_id),
        )
    return files
