from typing import Protocol

from tmis.integration_hub.queue.schemas import QueueItem


class SyncQueuePort(Protocol):
    def enqueue(self, item: QueueItem) -> None: ...

    def dequeue_next(self) -> QueueItem | None: ...

    def mark_running(self, item_id: str) -> None: ...

    def mark_done(self, item_id: str, detail: str) -> None: ...

    def mark_failed(self, item_id: str, error: str) -> QueueItem: ...

    def cancel(self, item_id: str) -> None: ...

    def get(self, item_id: str) -> QueueItem | None: ...

    def list_all(self) -> list[QueueItem]: ...

    def check_timeouts(self) -> list[QueueItem]: ...
