from typing import Protocol

from tmis.legal_copilot_framework.copilot.schemas import CopilotActivation, LegalCopilot


class CopilotStorePort(Protocol):
    def save(self, copilot: LegalCopilot) -> None: ...

    def get(self, copilot_id: str) -> LegalCopilot | None: ...

    def list_all(self) -> list[LegalCopilot]: ...


class CopilotActivationStorePort(Protocol):
    def save(self, activation: CopilotActivation) -> None: ...

    def get(self, firm_id: str, copilot_id: str) -> CopilotActivation | None: ...

    def list_for_firm(self, firm_id: str) -> list[CopilotActivation]: ...
