from typing import Protocol

from tmis.cabinet_knowledge.taxonomy.schemas import LegalDomain, TaxonomyNode


class TaxonomyStorePort(Protocol):
    def add(self, node: TaxonomyNode) -> None: ...

    def get(self, node_id: str) -> TaxonomyNode | None: ...

    def list_by_domain(self, domain: LegalDomain) -> list[TaxonomyNode]: ...

    def children_of(self, parent_id: str) -> list[TaxonomyNode]: ...

    def list_all(self) -> list[TaxonomyNode]: ...
